# Generated by Django 4.0.1 on 2024-11-04 09:03

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('avatar', models.ImageField(default='images/default.jpg', upload_to='uploads/')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('dataset'), models.Model),
        ),
    ]
